docs: add drs-filer in resources
elixir-europe/elixir-cloud-outline pull request #15
Opened 2020-09-02 16:26 UTC by sarthakgupta072

### Before Change

`mock-drs` was running on http://193.166.24.114/ga4gh/drs/v1/ui/.

### After Change

`mock-drs` is now running on http://193.166.24.114:9101/ga4gh/drs/v1/ui/.

`drs-filer` service is now running on http://193.166.24.114/ga4gh/drs/v1/ui/.

2020-09-02 16:35 UTC, uniqueg requested changes
One small issue, otherwise looks good. Thanks!

2020-09-02 16:35 UTC, uniqueg commented on resources/resources.md
> +| [CSC][loc-csc], Finland | [Docker Compose][res-docker-compose] | No | No | [API][depl-api-drs-filer-csc-compose] / [Swagger UI][depl-ui-drs-filer-csc-compose] | [![Status][badges-health-mock-drs-cs
* replace `[badges-health-mock-drs-csc-compose]` with `[badges-health-drs-filer-csc-compose]`
* add an entry for `[badges-health-drs-filer-csc-compose]` in the reference list below
* update the link for `[badges-health-mock-drs-csc-compose]` in the reference list below to account for the changed port

2020-09-02 16:40 UTC, sarthakgupta072 commented on resources/resources.md
> +| [CSC][loc-csc], Finland | [Docker Compose][res-docker-compose] | No | No | [API][depl-api-drs-filer-csc-compose] / [Swagger UI][depl-ui-drs-filer-csc-compose] | [![Status][badges-health-mock-drs-cs
Oh missed it. Will do

2021-03-04 08:15 UTC, uniqueg approved these changes

2021-03-04 08:15 UTC, merged